### PR TITLE
feat: add ability to skip ssl verification or pass CA bundle

### PR DESCRIPTION
**Pull request by raider444**
Issue #16

### CODE REVIEW

**Comment by raider444** [comment]
@nymous any chance this PR can be reviewed and merged soon?

**Comment by nymous** [comment]
Hey! Many thanks for the PR, with tests and docs! :heart: 
I did some touch-ups to it, mainly to replace the `str_to_bool` with Pydantic's `parse_obj_as`, which is not deprecated, returns actual booleans ^^', and since we depend on Pydantic anyway doesn't cost much. I also simplified the tests to keep only what they were about, and added some more to check the priority order.

Tell me what you think about it, and I'll be happy to merge!

**Comment by raider444** [comment]
> Hey! Many thanks for the PR, with tests and docs! ❤️ I did some touch-ups to it, mainly to replace the `str_to_bool` with Pydantic's `parse_obj_as`, which is not deprecated, returns actual booleans ^^', and since we depend on Pydantic anyway doesn't cost much. I also simplified the tests to keep only what they were about, and added some more to check the priority order.
> 
> Tell me what you think about it, and I'll be happy to merge!

Thanks! It looks reasonable.

**Review by nymous — APPROVED** [review]

**Comment by nymous** [comment]
Release 0.8.0 is out with this!
Thank you again!

**Pull request merged**
